/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as ItinerariesBarAlHikmanRouteImport } from './routes/itineraries.bar-al-hikman'
import { Route as ItinerariesDivingRouteImport } from './routes/itineraries.diving'
import { Route as ItinerariesSalalahRouteImport } from './routes/itineraries.salalah'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesBarAlHikmanRoute = ItinerariesBarAlHikmanRouteImport.update({
  id: '/itineraries/bar-al-hikman',
  path: '/itineraries/bar-al-hikman',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesDivingRoute = ItinerariesDivingRouteImport.update({
  id: '/itineraries/diving',
  path: '/itineraries/diving',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesSalalahRoute = ItinerariesSalalahRouteImport.update({
  id: '/itineraries/salalah',
  path: '/itineraries/salalah',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enquire': typeof EnquireRoute
  '/itineraries/bar-al-hikman': typeof ItinerariesBarAlHikmanRoute
  '/itineraries/diving': typeof ItinerariesDivingRoute
  '/itineraries/salalah': typeof ItinerariesSalalahRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enquire': typeof EnquireRoute
  '/itineraries/bar-al-hikman': typeof ItinerariesBarAlHikmanRoute
  '/itineraries/diving': typeof ItinerariesDivingRoute
  '/itineraries/salalah': typeof ItinerariesSalalahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enquire': typeof EnquireRoute
  '/itineraries/bar-al-hikman': typeof ItinerariesBarAlHikmanRoute
  '/itineraries/diving': typeof ItinerariesDivingRoute
  '/itineraries/salalah': typeof ItinerariesSalalahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enquire'
    | '/itineraries/bar-al-hikman'
    | '/itineraries/diving'
    | '/itineraries/salalah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enquire'
    | '/itineraries/bar-al-hikman'
    | '/itineraries/diving'
    | '/itineraries/salalah'
  id:
    | '__root__'
    | '/'
    | '/enquire'
    | '/itineraries/bar-al-hikman'
    | '/itineraries/diving'
    | '/itineraries/salalah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnquireRoute: typeof EnquireRoute
  ItinerariesBarAlHikmanRoute: typeof ItinerariesBarAlHikmanRoute
  ItinerariesDivingRoute: typeof ItinerariesDivingRoute
  ItinerariesSalalahRoute: typeof ItinerariesSalalahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/bar-al-hikman': {
      id: '/itineraries/bar-al-hikman'
      path: '/itineraries/bar-al-hikman'
      fullPath: '/itineraries/bar-al-hikman'
      preLoaderRoute: typeof ItinerariesBarAlHikmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/diving': {
      id: '/itineraries/diving'
      path: '/itineraries/diving'
      fullPath: '/itineraries/diving'
      preLoaderRoute: typeof ItinerariesDivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries/salalah': {
      id: '/itineraries/salalah'
      path: '/itineraries/salalah'
      fullPath: '/itineraries/salalah'
      preLoaderRoute: typeof ItinerariesSalalahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnquireRoute: EnquireRoute,
  ItinerariesBarAlHikmanRoute: ItinerariesBarAlHikmanRoute,
  ItinerariesDivingRoute: ItinerariesDivingRoute,
  ItinerariesSalalahRoute: ItinerariesSalalahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
